src/Entity/InscriptionEleve.php
<?php

namespace App\Entity;

use App\Repository\InscriptionEleveRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InscriptionEleveRepository::class)]
class InscriptionEleve
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    public function getId(): ?int
    {
        return $this->id;
    }
}
 

src/Entity/UsersEleves.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UsersElevesRepository;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UsersElevesRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class UsersEleves implements UserInterface,PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_naissance = null;

    #[ORM\Column(length: 255)]
    private ?string $lieu_naissance = null;

    #[ORM\Column(length: 255)]
    private ?string $sexe = null;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): static
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getLieuNaissance(): ?string
    {
        return $this->lieu_naissance;
    }

    public function setLieuNaissance(string $lieu_naissance): static
    {
        $this->lieu_naissance = $lieu_naissance;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): static
    {
        $this->sexe = $sexe;

        return $this;
    }

    

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }
}

src/Controller/InscriptionEleveController.php
<?php

namespace App\Controller;

use App\Entity\UsersEleves;
use App\Form\RegistrationFormEleveType;
use App\Repository\UsersElevesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

#[Route('/inscription/eleve', name: 'inscription_eleve_')]
class InscriptionEleveController extends AbstractController
{
    #[Route('/ajouter', name: 'ajouter')]
    public function ajouter(Request $request, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager): Response
    {
        $user = new UsersEleves();
        $form = $this->createForm(RegistrationFormEleveType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $user = $form->getData();
            $plainPassword = $form->get('plainPassword')->getData();
            
           
            $user->setPassword($plainPassword);
            $user->setRoles(['ROLE_ElEVE']);
            $entityManager->persist($user);
            $entityManager->flush();
            // do anything else you need here, like send an email

            return $this->redirectToRoute('inscription_eleve_ajouter');
        }

        return $this->render('secretaire/inscription_eleve/registerEleve.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }

    #[Route('', name: 'liste')]
    public function liste(UsersElevesRepository $usersElevesRepository): Response
        {
            $inscriptions = $usersElevesRepository->findBy([],[]);
            return $this->render('secretaire/inscription_eleve/listeEleve.html.twig', compact('inscriptions') 
            );
        }

    #[Route('/modifier/{id}', name: 'modifier')]
    public function modifier(Request $request, $id, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager): Response
        {

            $user = $entityManager->getRepository(UsersEleves::class)->find($id);
           
            $form = $this->createForm(RegistrationFormEleveType::class, $user);
            $form->handleRequest($request);
    
            if ($form->isSubmitted() && $form->isValid()) {
                // encode the plain password
                $user = $form->getData();
                $plainPassword = $form->get('plainPassword')->getData();
                
               
                $user->setPassword($plainPassword);
                $user->setRoles(['ROLE_ElEVE']);
                $entityManager->persist($user);
                $entityManager->flush();
                // do anything else you need here, like send an email
    
                return $this->redirectToRoute('inscription_eleve_liste');
            }
    
            return $this->render('secretaire/inscription_eleve/ModifierEleve.html.twig', [
                'registrationForm' => $form->createView(),
            ]);
        }

        #[Route('/supprimer/{id}', name: 'supprimer')]
        public function supprimer($id,UsersElevesRepository $usersElevesRepository, EntityManagerInterface $entityManagerInterface): Response
        {
            $user = $entityManagerInterface->getRepository(UsersEleves::class)->find($id);
            $supprimer=$usersElevesRepository->remove($user, true);
            return $this->redirectToRoute('inscription_eleve_liste');
        } 
    
}

templates/Secretaire/inscription_eleve/ListeEleve.html.twig
{% extends 'base.html.twig' %}

{% block title %}liste des Utilisateurs{% endblock %}

{% block body %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}


<div class="content-body">
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h4>Bienvenu</h4>
                   
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Eleve</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Liste</a></li>
                </ol>
            </div>
        </div>
        <!-- row -->

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"> <a href="{{ path('inscription_eleve_ajouter') }}" class="btn btn-warning">Ajouter un Eleve</a></h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-responsive-sm">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Nom</th>
                                        <th scope="col">Prenom</th>
                                        <th scope="col">Email</th>
                                        <th scope="col">Date Naissance</th>
                                        <th scope="col">Lieu Naissance</th>
                                        <th scope="col">Role</th>
                                        <th scope="col">Password</th>
                                        <th scope="col">Sexe</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                {% for user in inscriptions %} 
                                    <tbody>
                                        <tr>
                                            <td>{{ loop.index }}</td>
                                            <td>{{ user.nom}}</td>
                                            <td>{{ user.prenom }}</td>
                                            <td>{{ user.email }}</td>
                                            <td>{{ user.dateNaissance|date('d/m/Y')}}</td>
                                            <td>{{ user.lieuNaissance }}</td>
                                            <td class="badge bg-success">Eleve</td>
                                            <td>{{ user.password }}</td>
                                            <td>{{ user.sexe}}</td>
                                            <td>
                                                <a href="{{path('inscription_eleve_modifier',{id: user.id }) }}" class="btn btn-primary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                                                    <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                                                </svg></a>
                                                <a href="{{ path('inscription_eleve_supprimer', {'id': user.id}) }}" onclick="return confirm('Voulez-vous vraiment supprimer cet utilisateur ?')" class="btn  btn-danger"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                </svg></a>
                                            </td>
                                        </tr>
                                    </tbody>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div><a >Supprimer</a>

        </div>
    </div>
</div>
{% endblock %}

templates/Secretaire/inscription_eleve/modifierEleve.html.twig
{% extends 'base.html.twig' %}

{% block title %}Register{% endblock %}

{% block body %}
<div class="content-body">
        <div class="container-fluid">
            <div class="row page-titles mx-0">
                <div class="col-sm-6 p-md-0">
                    <div class="welcome-text">
                        <h4>Bienvenu</h4>
                        
                    </div>
                </div>
                <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Inscription</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Modifier</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->
            <div class="row">
                <div class="col-xl-12 col-xxl-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Form step</h4>
                        </div>
                        <div class="card-body">
                                <h4 class="text-center mb-4">Modifier un eleve</h4>
                               
                
                                
                                <div class="danger">
                                    {{ form_errors(registrationForm) }}
                                </div>

                                {{ form_start(registrationForm) }}
                                        <label><strong>Username</strong></label>
                                    {{ form_row(registrationForm.nom, {'attr':{'type':"text",' class':"form-control",'label':'Nom"' }}) }}  
                                    {{ form_row(registrationForm.prenom, {'attr':{'type':"text",' class':"form-control",'label':'prenom' }}) }}                                

                                    {{ form_row(registrationForm.email, {'attr':{'type':"email",' class':"form-control",'label':'Email' }}) }}
                                    {{ form_row(registrationForm.date_naissance, {'attr':{'type':"date",' class':"form-control",'placeholder':'dd-MM-yyyy'}}) }}  
                                    {{ form_row(registrationForm.lieu_naissance, {'attr':{'type':"text",' class':"form-control",'label':'Lieu Naissance' }}) }}  

                                    {{ form_row(registrationForm.plainPassword, {'attr':{'type':"password",' class':"form-control",'label':'Password','placeholder':'**************'}}, {
                                        label: 'Password'
                                    }) }}
                                    {{ form_row(registrationForm.sexe, {'attr':{'label':'Sexe' }}) }}
                                    {{ form_row(registrationForm.agreeTerms) }}
                                    <div class="text-center mt-4">
                                        <button type="submit" class="btn btn-primary btn-block">Modifier</button>
                                    </div>    
                                {{ form_end(registrationForm) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/Secretaire/inscription_eleve/registerEleve.html.twig
{% extends 'base.html.twig' %}

{% block title %}Register{% endblock %}


{% block body %}
<div class="content-body">
        <div class="container-fluid">
            <div class="row page-titles mx-0">
                <div class="col-sm-6 p-md-0">
                    <div class="welcome-text">
                        <h4>Bienvenu</h4>
                        
                    </div>
                </div>
                <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Inscription</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->
            <div class="row">
                <div class="col-xl-12 col-xxl-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Form step</h4>
                        </div>
                        <div class="card-body">
                                <h4 class="text-center mb-4">Inscription des Eleves</h4>
                               
                
                                
                                <div class="danger">
                                    {{ form_errors(registrationForm) }}
                                </div>

                                {{ form_start(registrationForm) }}
                                        <label><strong>Username</strong></label>
                                    {{ form_row(registrationForm.nom, {'attr':{'type':"text",' class':"form-control",'label':'Nom"' ,'placeholder':"nom"}}) }}  
                                    {{ form_row(registrationForm.prenom, {'attr':{'type':"text",' class':"form-control",'label':'prenom' ,'placeholder':"prenom"}}) }}                                

                                    {{ form_row(registrationForm.email, {'attr':{'type':"email",' class':"form-control",'label':'Email' ,'placeholder':"hello@example.com"}}) }}
                                    {{ form_row(registrationForm.date_naissance, {'attr':{'type':"date",' class':"form-control",'placeholder':'dd-MM-yyyy'}}) }}  
                                    {{ form_row(registrationForm.lieu_naissance, {'attr':{'type':"text",' class':"form-control",'label':'Lieu Naissance"' ,'placeholder':"lieu Naissance"}}) }}  

                                    {{ form_row(registrationForm.plainPassword, {'attr':{'type':"password",' class':"form-control",'label':'Password', 'placeholder':"***********"}}, {
                                        label: 'Password'
                                    }) }}
                                    {{ form_row(registrationForm.sexe, {'attr':{'label':'Sexe' }}) }}
                                    {{ form_row(registrationForm.agreeTerms) }}
                                    <div class="text-center mt-4">
                                        <button type="submit" class="btn btn-primary btn-block">Inscrire</button>
                                    </div>    
                                {{ form_end(registrationForm) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}